### ISSUE TITLE
Some questions about resume

### ISSUE THREAD

**Issue by JackSnowWolf** [yanyiju/Resume#1]
I'm also looking for a summer internship and it seems like your resume is quite good. Could you give me some suggestions about my resume?
Here is my resume link
[https://github.com/JackSnowWolf/JackSnowWolf.github.io/blob/master/doc/huchong_resume.pdf](url)

And do we need to add the summary part into resume? I guess we can write such things into cover letter.
Looking for your response!

**Comment by yanyiju** [comment]
Your link is not open.

**Comment by JackSnowWolf** [comment]
@yanyiju try this one:
[https://jacksnowwolf.github.io/doc/huchong_resume.pdf](url)

**Comment by yanyiju** [comment]
Your experience in CV is better than mine. Maybe you can make the page look much more clear for a HR officer if you place your skills and targets at the top? Best.
